### ISSUE TITLE
wiredep:app cannot find Bower packages

### ISSUE THREAD

**Issue by nogginfuel** [kestutis-stalmokas/firefoxOS-reminders#1]
I kept getting the following message after running the "grunt serve" command:

Running "wiredep:app" (wiredep) task
Cannot find where you keep your Bower packages

I looked around a few places online but couldn't find anything to resolve this issue.
Is there an out of date script or constructor? 
I followed the brief instructions in your Readme file.

All advice is appreciated. I'm really looking forward to exploring your product.

**Comment by stalmok** [comment]
I've commited a fix, should be ok now.

**Comment by nogginfuel** [comment]
Thanks, I'll download a fresh copy later this evening and give it another go. I appreciate the timely response.

**Comment by stalmok** [comment]
No problem mate, good luck.

**Comment by nogginfuel** [comment]
I just reran the effort. I think your fix really helped. Also I think part of the problem was I was using the built in Windows CMD and the Node CMD (not the GitBash / PowerShell).
