### ISSUE TITLE
Not Changing to Prompt Screen When Alarm Reached

### ISSUE THREAD

**Issue by nogginfuel** [kestutis-stalmokas/firefoxOS-reminders#2]
I did get the app spun up and so far I'm liking it (very intuitive). I did notice that when the countdown is reached it doesn't switch views to prompt the user to either same they are done or snooze it for another reminder.
Any thoughts on what is happening? I spun it up exactly as you have it described in the Readme.

///
This is a bit separate, but how would I go about adding a text box on the Alert view (when selecting done or selecting a future reminder time)? I would only want to capture this input field if they select a new reminder time (as kind of a audit to why you are resetting the alarm).

All your feedback is appreciated.

**Comment by stalmok** [comment]
Sorry for a late reply.

Are you running the app in firefoxOS simulator/phone or in the browser? Keep in mind that notifications are working only in simulator/phone because navigator.mozAlarms API is not availbale in the browser.

///
You can start by looking at app/scripts/controllers.js, I believe you're looking for `snooze` function.

**Comment by nogginfuel** [comment]
No worries, I just appreciate your help. I was trying to run it in the browser so it makes sense now why that wasn't working. I have installed the firefoxOS simulator and was able to get the app running after switching from directory to the url for localhost.

However, I'm still having the issue of the alert/snooze page not showing once the alert is reached. Is there a script I need to run or something else I need to do?

**Comment by stalmok** [comment]
Docs describe my development approach - in the browser. This is a lot faster as you don't need to update the app through simulator. But as I mentioned before, alerts aren't triggered in browser automatically. You can do this manually though - check how `initSnooze()` is called in `scripts/app.js`.

To test it in the simulator you don't even need to run `grunt serve`, just load `app` folder in Firefox WebIDE.

Good luck.

**Comment by nogginfuel** [comment]
I'll try to dig into the documentation over the next few days. I've also started downloading different webIDE runtimes. I'll see which one I can get to play nice with the repo. Thanks for the head's up on the alerts.
